# Hugolify content available https://github.com/Hugolify/hugolify-template/wiki/Content-sections

imports:
  - path: github.com/hugolify/hugolify-theme-3

  # Specific Lawerify
  - path: github.com/hugolify/lawyerify-example-site-associates
  - path: github.com/hugolify/lawyerify-theme
  - path: github.com/hugolify/lawyerify-decap-cms

  # Content
  # -> Hugolify content types and taxonomies available https://github.com/Hugolify/hugolify-template/wiki/Content-sections
  - path: github.com/hugolify/hugolify-theme-expertises
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme-persons-expertises
  - path: github.com/hugolify/hugolify-theme-persons-statutes
  - path: github.com/hugolify/hugolify-theme-publications-categories
  - path: github.com/hugolify/hugolify-theme-publications-expertises
  - path: github.com/hugolify/hugolify-theme-publications-persons
  - path: github.com/hugolify/hugolify-theme-publications

  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-decap-cms
