# Hugolify content available https://github.com/Hugolify/hugolify-template/wiki/Content-sections

imports:
  # Specific Lawerify
  - path: github.com/hugolify/lawyerify-example-site-independent
  - path: github.com/hugolify/lawyerify-theme

  # For exampleSite
  - path: github.com/hugolify/hugolify-theme-expertises
  - path: github.com/hugolify/hugolify-theme-posts-categories
  - path: github.com/hugolify/hugolify-theme-posts-expertises
  - path: github.com/hugolify/hugolify-theme-posts-tags
  - path: github.com/hugolify/hugolify-theme-posts

  # Core theme
  - path: github.com/hugolify/hugolify-theme
