_merge: deep
offices: /cabinets/:slug/
persons: /equipe/:slug/
persons_expertises: /equipe/expertises/:slug/
persons_offices: /equipe/cabinets/:slug/
statutes: /equipe/statuts/:slug/
posts: /actualites/:year/:year-:month-:day-:slug/
posts_expertises: /actualites/expertises/:slug/
authors: /actualites/auteurs/:slug/
categories: /actualites/categories/:slug/
tags: /actualites/tags/:slug/
publications: /parutions/:slug/
publications_categories: /parutions/categories/:slug/
publications_concerned: /parutions/personnes-concernees/:slug/
publications_expertises: /parutions/expertises/:slug/
