_merge: deep
places: /cabinets/:slug/
persons: /equipe/:slug/
persons_expertises: /equipe/expertises/:slug/
persons_places: /equipe/cabinets/:slug/
persons_statutes: /equipe/statuts/:slug/
posts: /actualites/:year/:year-:month-:day-:slug/
posts_expertises: /actualites/expertises/:slug/
authors: /actualites/auteurs/:slug/
categories: /actualites/categories/:slug/
tags: /actualites/tags/:slug/
publications: /parutions/:slug/
publications_categories: /parutions/categories/:slug/
publications_concerned: /parutions/personnes-concernees/:slug/
publications_expertises: /parutions/expertises/:slug/
realestates: /ventes-immobilieres/:slug/
realestates_persons: /ventes-immobilieres/personnes/:slug/
realestates_categories: /ventes-immobilieres/types/:slug/
